[tool.poetry]
name = "holamundo"
version = "1"
description = "holamundo"
authors = ["Monty Python"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.14"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
